version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5431:5431"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./../sql/DbGenerator.sql:/docker-entrypoint-initdb.d/DbGenerator.sql
    environment:
      - POSTGRES_USER=pgtest
      - POSTGRES_DB=pgtest
      - POSTGRES_PASSWORD=pgtest
      - DB_CONNECTION_STRING="host=192.168.112.2;port=5432;database=pgtest;username=pgtest;password=pgtest"
volumes:
  pgdata: