version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pgtest
      - POSTGRES_DB=pgtest
      - POSTGRES_PASSWORD=pgtest
      - DB_CONNECTION_STRING="host=localhost;port=5432;database=pgtest;username=pgtest;password=pgtest"
volumes:
  pgdata:

        